name: Отчет об ошибке
description: Отпишись, чтобы помочь с домашкой
title: '[Предмет] Ошибка в номере ...' 
labels: Ошибка
assignees:
  - IBIBENDUM
body:
  - type: markdown
    attributes:
      value: |
        > Заголовок для этого отчета будет **автоматически сгенерирован**.  
        > Вам не нужно заполнять поле заголовка вручную. Просто выберите предмет и укажите номер с ошибкой.
        > Метка предмета также выставляется **автоматически**
  - type: dropdown
    attributes:
      label: Предмет
      description: Выбери предмет, в задании которого допущена ошибка.
      options:
        - Матан
        - Дифуры
        - Анмех
        - Физика
    validations:
      required: true
  - type: input
    attributes:
      label: Номер с ошибкой
      description: В каком номере допущена ошибка?
      placeholder: Например, 1.23
    validations:
      required: true
  - type: textarea
    attributes:
      label: Описание ошибки
      description: Напиши кратко в чем заключается ошибка.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Верное решение
      description: Напиши свое решение.
    validations:
      required: false
