name: Update Issue Title

on:
  issues:
    types: [opened]

jobs:
  update-title:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        env:
          SCRIPT_PAT: ${{ secrets.script_pat }}
          REPO_NAME: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: python .github/workflows/mistake_format_title.py
